import { useCallback, useEffect, useMemo, useState } from "react";
import { PanelHeader } from "./components";
import { DependencyGraphView, DependencyListView } from "./DependencyViews";
import type { DependencyGraph, SearchResult, SmartSuggestion } from "./utils";
import { isPlainMissingResult, uniquePackages } from "./reportUtils";
import { ReportActions } from "./ReportActions";
import { ReportLogs } from "./ReportLogs";
import { ReportOverview } from "./ReportOverview";
import { ReportResultsTable } from "./ReportResultsTable";

export interface ReportViewProps { results: SearchResult[]; logs: string[]; dependencyGraph: DependencyGraph | null; packageCount: number; uniqueFoundCount: number; smartSuggestions: SmartSuggestion[]; searching: boolean; searchDuration: number | null; stageTimings?: Array<{ stage: string; durationMs: number }>; onClearLogs: () => void; onStatusChange: (status: string) => void; onApplySmartSuggestion: (suggestion: SmartSuggestion) => void; onRetryMissing: (packages: string[]) => void; onCancelPackage?: (packageName: string) => void; }

export function ReportView({ results, logs, dependencyGraph, packageCount, uniqueFoundCount, smartSuggestions, searching, searchDuration, stageTimings = [], onClearLogs, onStatusChange, onApplySmartSuggestion, onRetryMissing, onCancelPackage }: ReportViewProps) {
  const [activeTab, setActiveTab] = useState<"graph" | "list">("graph"); const [resultFilter, setResultFilter] = useState<"all" | "found" | "missing" | "error">("all"); const [selectedResults, setSelectedResults] = useState(new Set<string>());
  const failureGroups = useMemo(() => ({ missing: uniquePackages(results.filter(isPlainMissingResult)), timeout: uniquePackages(results.filter((r) => !r.found && r.status === "timeout")), rateLimited: uniquePackages(results.filter((r) => !r.found && r.status === "rateLimited")), error: uniquePackages(results.filter((r) => !r.found && r.status === "error")) }), [results]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.altKey && event.key === "1") setActiveTab("graph"); if (event.altKey && event.key === "2") setActiveTab("list"); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  const toggleFilter = useCallback((filter: "found" | "missing" | "error") => setResultFilter((current) => current === filter ? "all" : filter), []);
  const retryFailureGroup = useCallback((label: string, packages: string[]) => { if (!searching && packages.length) { onRetryMissing(packages); onStatusChange(`已回填 ${packages.length} 个${label}包，可重新检索`); } }, [onRetryMissing, onStatusChange, searching]);
  return <div className={`report-layout ${dependencyGraph ? "has-deps" : ""}`}><ReportOverview results={results} packageCount={packageCount} uniqueFoundCount={uniqueFoundCount} searching={searching} searchDuration={searchDuration} stageTimings={stageTimings} smartSuggestions={smartSuggestions} failureGroups={failureGroups} resultFilter={resultFilter} toggleFilter={toggleFilter} retryFailureGroup={retryFailureGroup} onApplySmartSuggestion={onApplySmartSuggestion} /><section className="panel report-panel"><div className="report-panel-header"><PanelHeader step="结果" title="来源验证" meta={searching ? "实时更新" : searchDuration != null ? `已完成 · ${(searchDuration / 1000).toFixed(1)}s` : "已完成"} />{results.length > 0 && <ReportActions results={results} selectedResults={selectedResults} searching={searching} packageCount={packageCount} uniqueFoundCount={uniqueFoundCount} searchDuration={searchDuration} onStatusChange={onStatusChange} onRetryMissing={onRetryMissing} />}</div><ReportResultsTable results={results} searching={searching} resultFilter={resultFilter} setResultFilter={setResultFilter} selectedResults={selectedResults} setSelectedResults={setSelectedResults} onStatusChange={onStatusChange} onCancelPackage={onCancelPackage} onRetryMissing={onRetryMissing} /></section>{dependencyGraph && <section className="panel dependency-panel"><PanelHeader step="扩展" title="依赖关系智能分析" meta={`共构建 ${dependencyGraph.summary.totalNodes} 个包节点，${dependencyGraph.summary.totalEdges} 条依赖链路`} /><div className="dependency-content-wrapper"><div className="tab-header"><button className={`tab-btn ${activeTab === "graph" ? "active" : ""}`} onClick={() => setActiveTab("graph")}>依赖关系图谱<span className="kbd-hint">Alt+1</span></button><button className={`tab-btn ${activeTab === "list" ? "active" : ""}`} onClick={() => setActiveTab("list")}>依赖清单列表<span className="kbd-hint">Alt+2</span></button></div>{activeTab === "graph" ? <DependencyGraphView graph={dependencyGraph} /> : <DependencyListView graph={dependencyGraph} />}</div></section>}<ReportLogs logs={logs} searching={searching} onClearLogs={onClearLogs} onStatusChange={onStatusChange} /></div>;
}
