import { sourceNames, type Method } from "./types";
import { MAX_HISTORY_FIELD_CHARS, MAX_INPUT_CHARS, MAX_RESULT_FIELD_CHARS, MAX_SEARCH_LOGS, MAX_SEARCH_RESULT_SCAN, MAX_SEARCH_RESULTS, MAX_SOURCE_CHARS, MAX_STATUS_CHARS, MAX_VERSION_CHARS, type DependencyDiagnostic, type DependencyGraph, type HistoryRecord, type PublicSettings, type SearchResponse, type SearchResult } from "./utils-types";

const VALID_METHODS: Method[] = ["auto", "devtools", "remotes", "github", "base", "version", "biocManager", "checkSystem"];
const DEFAULT_PINNED_METHODS: Method[] = ["auto", "base", "biocManager", "github"];
const encoder = new TextEncoder();
export const utf8Length = (value: string) => encoder.encode(value).length;
export function truncateUtf8Bytes(value: string, limit: number) { if (utf8Length(value) <= limit) return value; let bytes = 0; let out = ""; for (const c of value) { const n = utf8Length(c); if (bytes + n > limit) break; bytes += n; out += c; } return out; }
export function safeStatusText(value: unknown) { const text = truncateUtf8Bytes(String(value ?? "").trim().replace(/[\p{C}]/gu, ""), MAX_STATUS_CHARS); return text || "未知错误"; }
export function safeText(value: unknown, limit: number) { return truncateUtf8Bytes(String(value ?? "").trim().replace(/[\p{C}]/gu, ""), limit); }
export const safeBoolean = (value: unknown) => value === true;
export const safeRunId = (value: unknown) => typeof value === "number" && Number.isSafeInteger(value) && value > 0 ? value : 0;
export function safeSource(value: unknown) { const source = safeText(value, MAX_SOURCE_CHARS); return Object.prototype.hasOwnProperty.call(sourceNames, source) ? source : "none"; }
export function safeStatus(value: unknown) { const raw = typeof value === "string" ? value : ""; return ["found", "notFound", "timeout", "rateLimited", "error"].includes(raw) ? raw : "notFound"; }
export function safeStage(value: unknown) { const raw = typeof value === "string" ? value : ""; return ["queued", "cacheHit", "searching", "retrying", "final"].includes(raw) ? raw : "final"; }
export const sanitizeStatus = safeStatus;
export const sanitizeSearchStage = safeStage;
export function asRecord(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
export function asArray<T>(value: T[] | unknown): T[] { return Array.isArray(value) ? value : []; }
export function mapBounded<T, U>(items: readonly T[], limit: number, mapper: (item: T) => U) { const out: U[] = []; for (let i = 0; i < items.length && i < Math.max(0, Math.floor(limit)); i++) out.push(mapper(items[i])); return out; }
export function sanitizeSearchResult(value: unknown): SearchResult { const r = asRecord(value); return { package: safeText(r.package, MAX_RESULT_FIELD_CHARS), requestedVersion: safeText(r.requestedVersion, MAX_VERSION_CHARS), latestVersion: safeText(r.latestVersion, MAX_VERSION_CHARS), repository: safeText(r.repository, MAX_RESULT_FIELD_CHARS), realName: safeText(r.realName, MAX_RESULT_FIELD_CHARS), source: safeSource(r.source), found: safeBoolean(r.found), message: safeStatusText(r.message), status: safeStatus(r.status), stage: safeStage(r.stage) }; }
export function resultIdentityKey(r: SearchResult) { const caseSensitive = r.source === "github"; const normalize = (value: string) => caseSensitive ? value : value.toLocaleLowerCase(); return [normalize(r.package), r.requestedVersion, r.source, normalize(r.repository), normalize(r.realName)].join("\u0001"); }
export function formatError(error: unknown) { try { return safeStatusText(error instanceof Error ? error.message : String(error)); } catch { return "未知错误"; } }
export const isActiveInputLine = (value: string) => Boolean(value.trim()) && !value.trim().startsWith("#");
export function nonEmptyLineCountExceeds(value: string, limit: number) { let count = 0; for (const line of value.split(/\r?\n/)) if (isActiveInputLine(line) && ++count > limit) return true; return false; }
export function dedupeBoundedResults(items: readonly unknown[], limit: number, scanLimit: number) { const out: SearchResult[] = []; const indexes = new Map<string, number>(); for (let i = 0; i < items.length && i < Math.max(0, Math.floor(scanLimit)); i++) { const item = sanitizeSearchResult(items[i]); const key = resultIdentityKey(item); const index = indexes.get(key); if (index !== undefined) out[index] = item; else if (out.length < Math.max(0, Math.floor(limit))) { indexes.set(key, out.length); out.push(item); } } return out; }
export function sanitizeSearchResponse(value: unknown): SearchResponse { const r = asRecord(value); const out: SearchResponse = { runId: safeRunId(r.runId), results: dedupeBoundedResults(asArray(r.results), MAX_SEARCH_RESULTS, MAX_SEARCH_RESULT_SCAN), logs: mapBounded(asArray(r.logs), MAX_SEARCH_LOGS, safeStatusText), stopped: safeBoolean(r.stopped), stageTimings: Array.isArray(r.stageTimings) ? r.stageTimings.slice(0, 10).map((v) => { const t = asRecord(v); return { stage: safeStatusText(t.stage || "未知阶段"), durationMs: Math.max(0, Math.min(86400000, Number(t.durationMs) || 0)) }; }) : [] }; if (r.dependencyGraph) { const g = asRecord(r.dependencyGraph); out.dependencyGraph = { roots: asArray(g.roots).map(String), nodes: asArray(g.nodes).map((v) => { const n = asRecord(v); return { package: String(n.package), source: String(n.source), version: String(n.version), depth: Number(n.depth), rootPackages: asArray(n.rootPackages).map(String), directDependencyCount: Number(n.directDependencyCount), heavyDependencyCount: Number(n.heavyDependencyCount), status: String(n.status) }; }), edges: asArray(g.edges).map((v) => { const e = asRecord(v); return { from: String(e.from), to: String(e.to), relation: String(e.relation), strength: String(e.strength), depth: Number(e.depth) }; }), summary: (() => { const s = asRecord(g.summary); return { totalNodes: Number(s.totalNodes), totalEdges: Number(s.totalEdges), heavyNodes: Number(s.heavyNodes), lightNodes: Number(s.lightNodes), sharedNodes: Number(s.sharedNodes) }; })() }; } return out; }
export function sanitizeHistoryRecord(value: unknown): HistoryRecord { const r = asRecord(value); return { id: safeText(r.id, 64), command: safeText(r.command, MAX_HISTORY_FIELD_CHARS), packageName: safeText(r.packageName, MAX_RESULT_FIELD_CHARS), version: safeText(r.version, MAX_VERSION_CHARS), toolName: safeText(r.toolName, MAX_RESULT_FIELD_CHARS), createdAt: safeText(r.createdAt, 32), input: safeText(r.input, MAX_INPUT_CHARS), method: VALID_METHODS.includes(r.method as Method) ? r.method as Method : "auto", conditional: safeBoolean(r.conditional), installDependencies: safeBoolean(r.installDependencies), showRemoteVersion: safeBoolean(r.showRemoteVersion), verifyInstall: safeBoolean(r.verifyInstall), cranMirror: safeText(r.cranMirror, MAX_RESULT_FIELD_CHARS) }; }
export function sanitizePublicSettings(value: unknown): PublicSettings { const s = asRecord(value); const pinned = Array.isArray(s.pinnedMethods) ? s.pinnedMethods.filter((v, i, a): v is Method => typeof v === "string" && VALID_METHODS.includes(v as Method) && a.indexOf(v) === i) : []; const integer = (v: unknown, min: number, max: number, fallback: number) => typeof v === "number" && Number.isSafeInteger(v) && v >= min && v <= max ? v : fallback; return { proxy: safeText(s.proxy, MAX_RESULT_FIELD_CHARS), githubTokenConfigured: safeBoolean(s.githubTokenConfigured), cranMirror: safeText(s.cranMirror, MAX_RESULT_FIELD_CHARS) || "https://cloud.r-project.org", rLibPath: safeText(s.rLibPath, MAX_RESULT_FIELD_CHARS), fullSearch: safeBoolean(s.fullSearch), searchConcurrency: integer(s.searchConcurrency, 1, 12, 6), archiveGithubMajorGap: integer(s.archiveGithubMajorGap, 0, 10, 1), conditional: safeBoolean(s.conditional), installDependencies: safeBoolean(s.installDependencies), showRemoteVersion: safeBoolean(s.showRemoteVersion), useCache: safeBoolean(s.useCache), maxCacheEntries: integer(s.maxCacheEntries, 1, 10000, 1000), useFilter: safeBoolean(s.useFilter), resolveDependencies: safeBoolean(s.resolveDependencies), maxDependencyDepth: integer(s.maxDependencyDepth, 1, 5, 2), includeLightDependencies: safeBoolean(s.includeLightDependencies), maxDependencyNodes: integer(s.maxDependencyNodes, 1, 500, 100), pinnedMethods: pinned.length ? pinned : [...DEFAULT_PINNED_METHODS], pipIndex: safeText(s.pipIndex, MAX_RESULT_FIELD_CHARS) || "https://pypi.org", condaChannels: Array.isArray(s.condaChannels) ? s.condaChannels.filter((v): v is string => typeof v === "string").map((v) => safeText(v, MAX_RESULT_FIELD_CHARS)).filter(Boolean).slice(0, 20) : ["conda-forge", "bioconda"] }; }
export function diagnoseDependencyGraph(graph: DependencyGraph): DependencyDiagnostic[] { const out: DependencyDiagnostic[] = []; const adjacency = new Map<string, string[]>(); graph.edges.forEach((e) => adjacency.set(e.from, [...(adjacency.get(e.from) ?? []), e.to])); const visiting = new Set<string>(), visited = new Set<string>(), cycles = new Set<string>(); function visit(node: string, path: string[]) { if (visiting.has(node)) { const cycle = path.slice(path.indexOf(node)).concat(node), key = [...cycle].sort().join("|"); if (!cycles.has(key)) { cycles.add(key); out.push({ type: "cycle", packages: cycle, detail: `检测到循环依赖：${cycle.join(" -> ")}` }); } return; } if (visited.has(node)) return; visiting.add(node); (adjacency.get(node) ?? []).forEach((child) => visit(child, [...path, node])); visiting.delete(node); visited.add(node); } graph.nodes.forEach((n) => visit(n.package, [])); const versions = new Map<string, Set<string>>(); graph.nodes.forEach((n) => { if (n.version !== "unknown") { const set = versions.get(n.package.toLowerCase()) ?? new Set<string>(); set.add(n.version); versions.set(n.package.toLowerCase(), set); } }); versions.forEach((set, key) => { if (set.size > 1) out.push({ type: "version-conflict", packages: [key], detail: `${key} 存在多个版本：${[...set].join(", ")}` }); }); return out; }
